#!/bin/bash -l
# NOTE the -l (login) flag!
#
#SBATCH -J trainChestVal.py
#SBATCH -o chest_model.out
#SBATCH -e chest_model.err
# Default in slurm
#SBATCH --nodes=1
#SBATCH --tasks-per-node=10
#SBATCH --partition=datasci
#SBATCH --gres=gpu:1

#purge and load the correct modules
module purge > /dev/null 2>&1
module load cuda
module load python

#The command below is to execute our GPU program
KERAS_BACKEND=tensorflow 

python train.py model
python test.py model output
